### ISSUE TITLE
Followup to the "mismatch in telemetry between aca_l0 and cheta" issue

### ISSUE THREAD

**Issue by javierggt** [sot/agasc#108]
It turns out that issue #70 was not the whole story...

In the current implementation, I first query for a single MSID ('AOACMAG{slot}') and use that to set the times byt finding the intersection of `msid.times` with the times in `slot_data` from `mica.archive.l0`. That does not always work... e.g. OBSID 50255, agasc_id 991559968.

In the changes for issue #70, I started using `fetch.Msid` and `fetch.Msidset` instead of `fetch.MSID` and `fetch.MSIDset`. It took me a while to realize that the `bads` attribute is different depending on the **other** MSIDs in the set. For example, the following, the times for AOACMAG3, which I am using to define the times, are different when fetched together with AOACASEQ:
```
In [2]: msid = fetch.Msid('AOACMAG3', 605480583, 605480588)                                                                                                                               

In [3]: msid.times - 605480583.76560163                                                                                                                                                   
Out[3]: array([0.        , 1.0250001 , 2.05000007, 3.07500017, 4.10000026])

In [4]: msids = fetch.Msidset(['AOACASEQ', 'AOACMAG3'], 605480583, 605480588)                                                                                                             

In [5]: msids['AOACMAG3'].times - 605480583.76560163                                                                                                                                      
Out[5]: array([0.        , 1.0250001 , 3.07500017, 4.10000026])
```

as a result of this, `t=605480585.8156017` is missing from cheta telemetry but present in l0 slot data.

----->  "mismatch in telemetry between aca_l0 and cheta"

**Comment by jeanconn** [comment]
So, what is the requirement?  If there is a bad value for one of the required pieces (in this case I infer AOACASEQ?) it sounds like one shouldn't use the image data from then to calculate magnitude.  But it doesn't sound like a reason to discard all of the data for the star for that obsid.   Or am I misunderstanding?

**Comment by javierggt** [comment]
This is a bug. This error is no reason to discard the data.

This issue will serve as the description for the PR I will push tomorrow morning.
