### ISSUE TITLE
Implement a supplement time machine

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#128]
In order to resolve issues of testing older catalogs, implement some way of getting back to the supplement at any time in the past.  (More precisely, any time in the past which is after when we start the time machine going).

**Comment by javierggt** [comment]
A typical way to do this is to implement a table which has a `last_modified` column. It is then easy to recreate the regular table at any given time.

In SQL, the regular table could be implemented using a view (https://www.sqlitetutorial.net/sqlite-create-view/).

This could also be implemented as a *historical* table that sits side-by-side the regular table, and whose records are never updated or removed, only added.

One detail is that currently many rows are "updated" with minute changes. This is something I thought we could change, so records are only updated if the change is significant (where that would have to be defined, something like `mag_diff > min(0.1, mag_uncertainty/10)` or so). This would reduce the size of the historical table.

**Comment by jeanconn** [comment]
For a star that is updated more than once.  How do you see the 'last_modified' column helping?  I think we'd need to have multiple entries for the star which would be a different data structure for the mags table.

**Comment by javierggt** [comment]
Yes, the following paragraphs are important too. You need to have a second table:
- a view in SQL or
- a historical table where you do not remove rows

**Comment by jeanconn** [comment]
Ha.  I didn't realize it was all one implementation idea.  Thanks @javierggt !

**Comment by taldcroft** [comment]
The historical table can work, but I think it would require a substantial amount of effort and new code. Remember we also need to track the `bad` table (and obs_status would be nice). So this means making new data products and the code to make them, then the code to recreate the supplement at a particular date, and then tests to prove that it all works.

Using a git repo, I imagine a pretty small code footprint to just copy the supplement into a git repo, git commit with a version name like `2021-11-29` which is taken from the `last_updated['supplement']` field. Literally of order a dozen lines of code?

When proseco gets run, that version is stored in the proseco pickle. Later on when we need it, go to the repo and `git checkout 2021-11-29` (using the version in the pickle) and you have *the exact* file that was previously used, not a re-creation that we believe has the same values.

The only uncertainty I have is about how big the repo would get with time. I think in practice git is pretty efficient and clever, but hard to say.

**Comment by javierggt** [comment]
I was thinking of this, and one option is to store the tables as text files and version that. I figure that at least in this way the size will not increase quickly. If one versions compressed binaries, I believe the diffs are going too large.

One can then have a simple function to generate an h5 from the repository data.

**Comment by taldcroft** [comment]
Yeah, that can work and be efficient. I was going to say we don't need it because updates take only 13 Mb/week (3.4 Gb in 5 years), but thinking of syncing this onto my laptap made me realize that size matters just a bit. Interestingly I wrote the mags table to ECSV for kicks and found that it is just 3.4 Mb as text compared to 19 Mb in the current HDF5. 

Definitely there is something wrong with the H5 file, and maybe if it was compressed properly then maybe the git repo of just the H5 files would be small enough.

**Comment by taldcroft** [comment]
With https://github.com/sot/agasc/issues/127#issuecomment-998147450 the file is just 1.8 Mb, so we could forget about version control and just store each version separately in per-year directories like @jeanconn said. That's going to be around 0.5 Gb for 5 years.

**Comment by taldcroft** [comment]
Here is a fancy way of saying what @javierggt said: https://itnext.io/crud-tables-need-to-die-93d213b0d18a.

**Comment by jeanconn** [comment]
This is complete for now with /proj/sot/ska/data/agasc/time_machine/update_agasc_supplement_history.sh .
