### ISSUE TITLE
Weekly process seems to fail without any message

### ISSUE THREAD

**Issue by javierggt** [sot/agasc#156]
This week we got another case of failure in the weekly processing, and it is not clear what caused it. As a result, there is no weekly report for this week.

- The weekly update ran on `2023:254` (that's Sunday September 10 2023). It is set to run at 18:50.
- All relevant files were last updated around Sep 10 19:20 (supplement, fits files, obs_status.yml), so the magnitude update succeeded.
- the `supplement_reports/weekly/2023:254` exists, which means the reporting generation started.
- there is no symlink, no index file, and no call_args.yml, so the report generation did not finish.
- there is no error in the log file, so I do not know why it stopped.

The last lines of the log show the process just ended while processing one star, without any error message:
```
2023-09-10 19:39:01,681   Getting telemetry for AGASC ID=1201020040, OBSID=28874, mp_starcat_time=2023:244:03:27:46.987
2023-09-10 19:39:02,012     Adding magnitude estimates
2023-09-10 19:39:02,012     magnitude from images...
2023-09-10 19:39:02,036     magnitude from images... 2753 samples: 15.00...
2023-09-10 19:39:02,037     Adding star position
2023-09-10 19:39:02,038     star position. AGASC_ID=1201020040, 2753 samples, (871.0711687324691, -2242.5528470967224)...
2023-09-10 19:39:02,038     Correcting for droop
2023-09-10 19:39:02,038     Correcting for responsivity
2023-09-10 19:39:02,076   Getting telemetry for AGASC ID=1201020040, OBSID=27086, mp_starcat_time=2023:255:11:54:58.283

```

I am guessing that the process was killed. This happened roughly 50 minutes after it started.

**Comment by jeanconn** [comment]
Looking at dmesg output on kady it looks like out-of-memory was the issue.  

```
[5544475.728757] Out of memory: Killed process 3836531 (agasc-update-ma) total-vm:25187740kB, anon-rss:14522832kB, file-rss:4kB, shmem-rss:4kB, UID:1023 pgtables:47364kB oom_score_adj:0
[5544531.775981
```

**Comment by javierggt** [comment]
It seems that this is an issue with running out of memory. Apparently, this issue caused postfix to die.

Inspecting the log from the latest run, the last line was:
```
2024-02-19 03:16:21,002   Getting telemetry for AGASC ID=437658408, OBSID=43705, mp_starcat_time=2024:043:17:44:57.579
```

This is during the report generation. As a result, the supplement and fits files in the `rc` folder are up to date, because the report generation happens after that.

Interestingly, the last star in the log is not a star with many observations (it has 3). These are the 25 stars with the most observations in the period between `2024-01-19` and `2024-02-18` (not all are updated, because the script checks the last time it was updated against the last observation):

```
 agasc_id   n 
---------- ---
 525732488 201
 525735456 184
 525735976 156
 525732232 116
 525609504 105
 261621400  98
 261629720  97
 525736400  87
 261619776  85
 261623040  75
1201406184  73
 746455152  64
 335028240  53
1201406992  43
 525740136  39
 335029808  36
 261624456  31
1201411288  28
1091436944  27
1091443144  25
 335022112  24
1091443112  23
1059718384  22
 615907528  22
 104202616  21
```

I ran a script through memray for the top 5 stars in the list above.. During the update part of the run, the memory reached ~2.2GB. During the report part, memory usage peaked around 3.8GB, and mostly stayed around 3.2GB. I put the report [here](https://cxc.cfa.harvard.edu/mta/ASPECT/jgonzalez/agasc/issue-156/memray-flamegraph-run.py.346307.html), if you are interested.

**Comment by javierggt** [comment]
I ran the update script again through memray, this time including all stars. It finished without problem within an hour, but it did use a lot of memory. Here is a picture of the memory usage:

![newplot](https://github.com/sot/agasc/assets/140523/626fd6df-b6e5-4fff-9552-c44f3eb53192)

You can see that heap memory peaks around 18GB (I believe the machine has 16GB RAM). Heap memory is already at 10GB only ten minutes into the run, before the big stars show up. You can see the big ones because they give spikes in memory starting at 16:08. The main update ends around 16:20, and from then on it is writing the reports. Thats about 40 minutes in the reports, but memory is not an issue there, as it increases slowly.

So... what do we learn:
- it is not an issue with the reports (reports are slow but do not take all that memory)
- it is not an issue with big stars
- it is a constant increase from the beginning

Independently of the memory issue, notice that this process finished in one hour. The weekly job is scheduled to start at 18:50 on Sunday, but it crashed after 04:00 on Monday. Why is that? Why so long? If there are other processes, it will have to use more swap, and that can make it slower.

**Comment by taldcroft** [comment]
This has the feel of a memory leak where data from each processing is maintained even after it is no longer needed. Maybe some reference to the data persists?

**Comment by javierggt** [comment]
The following minimal script produces the behavior:
```
#!/usr/bin/env python                                                                                  


from agasc.supplement.magnitudes import star_obs_catalogs
from tqdm import tqdm
import numpy as np


print("loading star_obs_catalogs")
star_obs_catalogs.load("2024:049:23:52:07.231")
print("loaded star_obs_catalogs")

agasc_ids = np.random.choice(
    star_obs_catalogs.STARS_OBS['agasc_id'],
    size=100,
    replace=False
)

for agasc_id in tqdm(agasc_ids):
    star_obs = star_obs_catalogs.STARS_OBS[
        star_obs_catalogs.STARS_OBS["agasc_id"] == agasc_id
    ]
```

Here is a picture of the memory usage:
![newplot (1)](https://github.com/sot/agasc/assets/140523/ef645035-0162-4754-bc09-c002724742c7)

and here is the same picture while commenting out the loop:
![newplot (2)](https://github.com/sot/agasc/assets/140523/7865b996-c89d-428e-943b-00970c02bfb4)

This means the problem is in the statement within the loop. `star_obs_catalogs.STARS_OBS` is an astropy `Table`.
