### ISSUE TITLE
Idea for agasc updates: testing and better API and legacy compatibility

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#31]
This is an idea for consideration so we can promote Ska3 without a known set of test fails for `agasc` causing a red mark on our ska_testr results.

It seems we need a new release of Ska3-flight and Ska3-matlab anyway for the mica dark cal file handle leak problem, here is an idea for agasc improvements that Malgosia could lead:
- Modify the test mp_get_agasc() function to use a fixed radius of 0.6 deg and to write out the results to a gzipped FITS file.  These will become the new reference standard and will be included in the package distribution.  Label the files in a way that includes the info that they are from AGASC 1.6.
- Now modify the tests to use a radius=0.5 deg in testing and use those pre-generated files and compare with results for agasc_1p6.h5.
- Remove all random elements from testing.  It should be fixed and deterministic.
- You'll need to bundle package data in the setup.py.  See https://github.com/sot/proseco/blob/master/setup.py#L17 for an example (but the data should be in `agasc.tests`).
- Update the code so that if `agasc_file` is provided that is not an absolute file, then it looks for `Path(os.environ['SKA'], 'data', 'agasc', agasc_file)`.  If not provided the default should be ~~'miniagasc_1p7.h5'~~ 'miniagasc.h5'.  (Use `Path` everywhere, not `os.path`).
- I think this can be a Ska3-only update, so update the version to 4.6.
- ~~When this is installed and starcheck-py3 is promoted, we could optionally revert the miniagasc.h5 link to point back at agasc_1p6.h5 for back-compatibility with legacy code in Ska2.~~

Thoughts?  We can limp through the finish line without this, but it would be nicer with something like this.

**Comment by jeanconn** [comment]
Also, which code do we need to worry about for back compatibility in Ska2 with the miniagasc?

**Comment by taldcroft** [comment]
> If DS 10.7 goes on OCT 20 with AGASC 1.7 we could have passing tests on HEAD for the OCT 24 date without modification.

Not in time for Oct 18 Ska3 promotion.  Sure, we can red-line the test as a fail that will be fixed, eventually.  It's just nicer to not have to make a story.

> The test fixes I suggested would work in the interim for agasc, and these are never fails on GRETA (no mp_get_agasc).

With the proposal we can have tests passing on all platforms this week.  :tada:  This isn't just a trivial thing, we don't really have comprehensive tests otherwise that the `agasc` package is doing the right thing except on HEAD flight-64.

> The h5 files are really the reference at this point anyway, so maybe we should stop validating against mp_get_agasc.

Agreed, kind of.  It is a nice thing to generate the reference FITS files using `mp_get_agasc` (just once) since it provides verification that our local HDF5 version does match the DS / FOT Matlab version from FITS.  Once the new files are in the package then you are robust against platform diffs (e.g. 32-bit or Windows) or numpy updates that introduce those "who could have imagined" diffs.

> which code do we need to worry about for back compatibility in Ska2 with the miniagasc?

Nothing in mind, just being a stickler for strict "back-compatibility".  But I did mark that as optional and I agree in practice it is likely a non-issue.

**Comment by jeanconn** [comment]
Regarding:

> Not in time for Oct 18 Ska3 promotion. Sure, we can red-line the test as a fail that will be fixed, eventually. It's just nicer to not have to make a story.

I wasn't sure we were solid on that Oct 18 date out of SSAWG (got the impression that we might just plan to bring everything together for promotion the next week).

**Comment by taldcroft** [comment]
> I wasn't sure we were solid on that Oct 18 date out of SSAWG

Not sure either (you had made a good point about review fatigue).  Would this one point change your opinion of the best path forward?

**Comment by jeanconn** [comment]
This one point does not change my opinion of the best path forward, but if all the tests look fine for our TRR date that does suggest to me that these changes and test fixes don't need to be a high priority item.  I assume your recommended changes to the agasc module api is are a higher priority (medium?) item and maybe these test fixes should go at the same time.

**Comment by taldcroft** [comment]
Now that `agasc` will be used directly in FOT mission planning and load review on multiple platforms, I'm not happy with skipping the comprehensive regression tests on most platforms.  I'm also not keen on our success depending on DS getting their release out on time.  So testing is actually the priority for me.
