### ISSUE TITLE
Support agasc supplement

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#47]
Support agasc supplement

Our ideas so far include:
 - [ ] returned data should indicate if there is supplement data for a star
 - [ ] supplement magnitudes and error should replace catalog magnitudes by default
 - [ ] there should be an option to correct magnitudes for "droop"

**Comment by jeanconn** [comment]
On the MATLAB side we're tracking this at 

https://occ-cfa.cfa.harvard.edu/browse/MATLAB-11671

**Comment by jeanconn** [comment]
I have other implementation questions, for example, should there be different handling of "bad" stars (stars in the "bad" table of the agasc supplement) in the get_agasc_cone and get_star(s) methods?

**Comment by jeanconn** [comment]
Some of this in #48 .

**Comment by taldcroft** [comment]
This is completely done.
