### ISSUE TITLE
Rename `ok` obs status column to `status`

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#60]
We agreed to use the name `status` with an int value where 0 is ok/good and 1 is bad.

The available options `ok` and `bad` should be listed in the argparse help (with `false` and `true` removed).

The `supplement.rst` example will need to be updated accordingly.

**Comment by javierggt** [comment]
Regarding this... I am assuming this also means changing the meaning so True becomes 0, and False becomes 1 (which is the opposite of the implicit bool-int conversion)
