### ISSUE TITLE
Help on --bad-star-source does not match code behavior

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#64]
The help file says there is a default, but not really.
```
  --bad-star BAD_STAR   Bad star.
  --bad-star-source BAD_STAR_SOURCE
                        Source identifier indicating provenance (default=max existing source + 1)
  --comments COMMENTS   Comments for status override.
  --log-level {debug,info,warning,error}
  --dry-run             Dry run (no actual file or database updates)
(ska3) ➜  agasc git:(update-script-fixes) python agasc/scripts/update_obs_status.py --bad-star=175379112 
Traceback (most recent call last):
  File "agasc/scripts/update_obs_status.py", line 235, in <module>
    main()
  File "agasc/scripts/update_obs_status.py", line 214, in main
    status = parse_obs_status_args(
  File "agasc/scripts/update_obs_status.py", line 89, in parse_obs_status_args
    raise RuntimeError('If you specify bad_star, you must specify bad_star_source')
RuntimeError: If you specify bad_star, you must specify bad_star_source
```

**Comment by javierggt** [comment]
ah! right.

In the original mica script, that was the default behavior: max existing source + 1. We had discussed to have a fixed source for stars flagged bad based on the magnitude data, so the update-mag-supplement script used that as default. In other words: there were two defaults, depending on the script.

When I merged the functionality, I missed that.

I think this should be fixed. There are a couple of options and the help string needs to be updated in most cases:
- the default value depends on context (on which script you are calling),
- we choose one of the two defaults,
- we have no defaults.

**Comment by javierggt** [comment]
@jeanconn might have a preference.

**Comment by jeanconn** [comment]
I don't have a preference.  I think your outcomes end up being either:

- keep incrementing the "source" as new stars are added
- use a fixed "source" for stars added via the magnitude review process

The "source" ends up not being really that useful unless we end up needing to reevaluate a population of "bad" stars based on why they are in there (for example some of the stars in the starcheck bad list would also be more appropriately handled as magnitude updates... but that is neither here nor there).

**Comment by javierggt** [comment]
Those are the two defaults. To me, a "source" that just increases with each addition is not useful.

The subtlety you might have missed is that this script will be used in general, not just the magnitude review process. So the question I am asking is how will this script be used in the two typical use cases:
- the magnitude review process
- some other case (based on experience, will there be any?)

That is why I speak of two defaults, depending on which script you use:
- During the magnitude review process, one would normally call the `agasc-supplement-update` script (should this name be changed? now or never). Default is a fixed "source"
- In all other cases you would call `agasc-supplement-obs-status` (which basically replaces the script in mica, also: should this be renamed? now or never). This one could have the same default as the mica script, incrementing the source if none is provided.

Enabling this requires jumping through a couple of hoops.

**Comment by jeanconn** [comment]
The problem that you note "based on experience, will there be any" is that we haven't defined a good use case. 

I don't think we've used the "source" downstream in any code, so I would still collapse them and set one for "manually added stars" with notes in a text file or the wiki, one for the GAIA proper motion stars, and then add new "source" classifiers if needed.  But for promotion of agasc supplement, none of those thoughts matter?

In support of this, I think dropping the default altogether might be the simplest way forward.

**Comment by taldcroft** [comment]
I agree with just dropping the default.

**Comment by javierggt** [comment]
Great. I will remove the mention of a default from the help string.
