### ISSUE TITLE
Question about number of stars being processed

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#66]
```
ska3-kady$ python agasc/scripts/update_mag_supplement.py
Excluding bad stars
Skipping 80059 stars already in the supplement
Will process 2785 stars on 14399 observations
```
I'm curious about the 2785 stars. This should be the stars for the last 2 weeks right? Even considering the extreme case of 100 obsids in two weeks, each with 8 stars, all unique, that is only 800 stars.

**Comment by javierggt** [comment]
This output means the starting time is not two weeks prior, as it should be. Otherwise it would not even be considering 80K+ stars.

**Comment by taldcroft** [comment]
> This output means the starting time is not two weeks prior, as it should be.

I'm a little confused still then. The docs say it will be processing two weeks of stars.
```
parser.add_argument('--start',
                        help='Include only stars observed after this time.'
                             ' CxoTime-compatible time stamp.'
                             ' Default: now - 14 days.')
```

**Comment by javierggt** [comment]
yes, it would be a bug.
