### ISSUE TITLE
Need mechanism to set mag and mag_err manually

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#69]
This example shows a case of a star that is clearly much fainter than the catalog mag, at least 12th mag or fainter. If it was brighter than that it would have gotten found at least a few times in the repeated guide searches. We have talked about just marking this star `bad`, but this is not really the right thing because proseco and starcheck will still consider it to be 9.91 mag for spoiling and plotting.

Since none of our tools has the concept of a lower limit for mag, we need to do *something*. For instance just assign it to be 12.0 +/- 0.1 mag and mark those two star-obs as `bad`. For a case like this the `bad` star list seems inappropriate - the only issue with the star is that the catalog mag was incorrect, but now we have a robust way of encapsulating that information. 

Likewise a star that is too bright should be treated accordingly, by putting our best estimate of the mag into the supplement. Whether we remove the historical cases of this from the `bad` table makes no practical difference.

![image](https://user-images.githubusercontent.com/348089/106132931-97ebbc80-6132-11eb-9f7c-3545f0923a68.png)

**Comment by javierggt** [comment]
Now I am looking into this, and it is not a big issue as long as we do not require consistency with other secondary files produced by the magnitude updates. In other words: this star appears in the `mag_stats_agasc.fits` file. In that file it will still have the magnitude from the magnitude estimation procedure, if any.

Then one has to decide what is the required input:
- is it reasonable to require that all fields need to be provided?
   - agasc_id
   - mag_aca
   - mag_aca_error
   - last_obs_time
 
In the case you show, the star would not be in the supplement already. It would not be an update but an addition. Some questions:
- Do we want to allow updates as well?
- if a star is being updated, are all fields still required?
- do we want to allow this function/script to also remove records?

**Comment by taldcroft** [comment]
> Now I am looking into this, and it is not a big issue as long as we do not require consistency with other secondary files produced by the magnitude updates. 

I don't see a need for consistency there. I view the `mag_stats_agsc.fits` as the raw version of what the processing finds, while the `mags` table is the curated version for operations. Being different is fine, and indeed expected in these cases.

About what is required input, the first three are fine and not controversial. The `last_obs_time` seems like it is better to be automatically determined by the code so it is consistent with what the time would be for a nominal "good" mag update. In other words, as a reviewer entering this data, I would not be certain of what exact value to use for that time. Maybe it can be optionally specified, just in case we need a manual override.

> Do we want to allow updates as well?

Yes. Is the plan to have a new status value (like 2) that indicates a manual override in addition to the comment. Is this set for every applicable star-obs, or ?

> if a star is being updated, are all fields still required?

Yes (with the previous caveat about `last_obs_time`)

> do we want to allow this function/script to also remove records?

I can't actually think of a reason we would need to remove a record. Maybe I'm missing something?

**Comment by javierggt** [comment]
> I can't actually think of a reason we would need to remove a record. Maybe I'm missing something?

No, I am just explicitly laying out what is needed.

**Comment by javierggt** [comment]
> Is the plan to have a new status value (like 2) that indicates a manual override in addition to the comment. Is this set for every applicable star-obs, or ?

That was not my plan. Do we want that?

**Comment by taldcroft** [comment]
> That was not my plan. Do we want that?

The question is what happens if we do a manual override and then another obs of that star happens. Will the new observation (assuming it is considered "good") override the manual setting? That would be my guess, in which case I think the weekly update code needs to know that a mag in the `mags` table was set manually and make any subsequent observations "suspect" so the ACA reviewer decides what to do. One way for the code to know is to look for any `status=2` in the obs-status table for that star. Maybe there is a better way?

**Comment by javierggt** [comment]
> The question is what happens if we do a manual override and then another obs of that star happens. Will the new observation (assuming it is considered "good") override the manual setting?

I thought about this, and my conclusion was that we would most probably manually edit stars that will never be observed again. This is the case for the example you posted at the top. If the star is going to be observed again, I would suggest setting the status of an observation so the automated process works.

I think you just want the numeric status ;-)

This seems like a lot of work to add a feature I am not convinced we need. The code as it is is baroque enough, and the scope of this has been creeping constantly.

**Comment by taldcroft** [comment]
Agreed, simple is better than complex. The case I was thinking about is when a star is first observed in week N and also planned into week N+1. For ER's there tends to be correlation between new stars showing up. In that case we may see it as bad in week N and override the mag, but it will still get into the products for the next week and get observed. We will accept this unless the catalog is so bad that it poses a safety risk.

But I agree the existing process will work OK in this case.
