### ISSUE TITLE
Generate YAML for the mission for suspect stars and populate obs table

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#71]
There used to be a page with the suspect star-obsid values for the whole mission. Is that still available? Presumably we want to go through those and basically sign-off (accept) on all or most of them to initially populate the obs_status table.

This follows the auto-generation of issue #57.

**Comment by javierggt** [comment]
We have decided to proceed with this after the following issues are fixed:
- #57 
- #81 
- #69
