### ISSUE TITLE
Get flake8 checks passing

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#73]
After #55, #56, and #58 get merged, then use autopep8 and manual fixes to get the flake8 check passing.

```
flake8 setup.py agasc --count --ignore=E402,W503,F541 --max-line-length=100 --statistics --show-source
```
See also https://occweb.cfa.harvard.edu/twiki/bin/view/Aspect/SkaPython#autopep8.

**Comment by javierggt** [comment]
argh... I have the opposite convention regarding breaking lines around binary operators. I break them after. Always.

**Comment by taldcroft** [comment]
> argh... I have the opposite convention regarding breaking lines around binary operators. I break them after. Always.

Autopep8 might be able to fix this? Anyway, we had a lot of discussion about this in astropy and there is now a reasonable level of convergence on breaking before. The main rationale is that really does make it easier to follow the logic because the operator is next to the operand and the operators are all lined up on the left so that also helps visually.

The VS code highlighting comes from (or should come from) your flake8 preferences.

**Comment by taldcroft** [comment]
BTW, until a year or so ago I always broke after the operator. It's not too hard to change and at least personally I was really happy with the new convention after seeing it in action.

**Comment by taldcroft** [comment]
Yes, autopep8 with the aggressive flag does it, and I think nicely shows the advantage of this convention:
```
autopep8 --select W504 -a --in-place agasc/supplement/magnitudes/update_mag_supplement.py

...
         outliers_new = agasc_stats[
-            (agasc_stats['n_obsids_ok'] > 0) &
-            (agasc_stats['selected_atol'] |
-             agasc_stats['selected_rtol'] |
-             agasc_stats['selected_color'] |
-             agasc_stats['selected_mag_aca_err'])
+            (agasc_stats['n_obsids_ok'] > 0)
+            & (agasc_stats['selected_atol']
+             | agasc_stats['selected_rtol']
+             | agasc_stats['selected_color']
+             | agasc_stats['selected_mag_aca_err'])
...
```
