### ISSUE TITLE
Disabled warnings question

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#75]
In `agasc/scripts/update_mag_supplement.py` there is code to disable all numpy warnings and all UserWarnings. 

What's the driver for these?

**Comment by javierggt** [comment]
There used to be some numpy warnings, and they appeared multiple times, cluttering the output. At various times I have set it up so it ignores them or it shows only the first one. I don't think this should show all warnings, but only the first time it occurs.

**Comment by taldcroft** [comment]
I'm still left wondering if those warnings are an indicator of something that could be improved in the code. Usually one should not have to suppress numpy and `UserWarning`, and in those rare cases it would be preferable to do so with a documented and localized context block instead of globally.

**Comment by javierggt** [comment]
While going over the logging I also looked into the warnings. These custom warning settings you saw are inside:

```
if __name__ == '__main__':
    ...
```

This section of the code is actually not called from the installed scripts, which call the entry point. As a result, these options have not been used in a while. I am removing them so they do not cause confusion, but I am keeping that section as a convenience.

**Comment by javierggt** [comment]
And a side note:

Perhaps it is better to not call the script in this way

```
python agasc/scripts/update_mag_supplement.py ...
```

but like this
```
agasc-supplement-update ...
```

**Comment by taldcroft** [comment]
About calling the script, I've been doing:
```
python -m agasc.scripts.update_mag_supplement ...
```
This is equivalent to `python agasc/scripts/update_mag_supplement.py ...` but you don't need to set the PYTHONPATH. I'm always hesitant to set the path because I will forget it is set in that window.

The problem with `agasc-supplement-update` is that this is tied to the installed version (assuming it exists), not the dev version in the current repo. I.e. if you run that within the `agasc` git repo, you are still running the installed `agasc` package, not the local one.

Takeaway - I think we need the `if __name__ == '__main__'` hook in each script, and it should do nothing more than call `main()` so that there is consistency with the entry-point version of the script.
