### ISSUE TITLE
Add obs/dwell date to 'obs' table in supplement

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#81]
Add obs/dwell date to 'obs' table in supplement

This should help us define dwells uniquely.

**Comment by taldcroft** [comment]
Related to this, I started poking into the code a bit more and it does look (at first glance) like the fundamental processing and bookkeeping is not dependent on unique obsid. (Good job @javierggt!).  Instead it is using `mp_starcat_time` as the key internally, and I see useful comments like 
```
    # Get all maneuvers and use this to create a table of NPM dwells
    # with a star catalog.
    #
    # Note that obsid is not unique for maneuvers since
    # after a safing action the obsid in telemetry can stay fixed while maneuvers
    # continue happening.
```
So maybe the action is really to replace `obsid` in the star-obs table with `mp_starcat_time` in terms of the unique key value (in a tuple with `agasc_id`). We could leave `obsid` in there for human convenience, but it wouldn't be part of a key. This would again move us toward the `obs` table updates coming for an automatically generated YAML file which the ACA reviewer then edits.

**Comment by javierggt** [comment]
Note: We have decided to use mp_starcat_date as the key to identify observations in the obs table in the supplement. We will keep the OBSID but it should not be used to determine the observations.
