### ISSUE TITLE
Follow-on issue for #83: last obs date 1997:365

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#87]
After following the functional test steps, these last obs dates look like they represent a default instead of the correct value. Even with no data the star was still "observed".
![image](https://user-images.githubusercontent.com/348089/108366948-f0a8f500-71c6-11eb-8a48-a73340dffd5c.png)

**Comment by javierggt** [comment]
Yes, that is a default. This is another example where the requirements were not specified from the beginning (the requirement being "to keep keeping a record of all observations, even failed ones"). Not that requirements were specified, as this steadily grew.

At the beginning, the number of observations was only that of successful observations, and only those appeared in the reports.

I think this can be fixed easily.

**Comment by taldcroft** [comment]
Not a lien for promotion, so you can consider it lower priority and take out of the Promote AGASC supplement project if fixing is a pain.
