### ISSUE TITLE
Follow-on issue for #83: nan catalog mag

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#88]
The catalog mag is listed as nan, which is not right.
![image](https://user-images.githubusercontent.com/348089/108367366-64e39880-71c7-11eb-8134-5e47069ec326.png)

**Comment by javierggt** [comment]
This issue has the same underlying reason as issue #87. This is a default value and the process ended before the correct value was set.

**Comment by taldcroft** [comment]
Neither of these are lien for promotion, so you can consider them lower priority and take out of the Promote AGASC supplement project if fixing is a pain.
