### ISSUE TITLE
Make sure ASCDS bits actually work

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#9]
Currently the testing initializes the ASCDS environment by sourcing ~/.ascrc, but (I think) this can succeed on CentOS-5 even though the actual tools no longer work.  So perhaps try actually running mp_get_agasc and mp_get_agascid before declaring success?

**Comment by jeanconn** [comment]
At which point should this fail out?  Should we run and fail mp_get_agasc or just run an assert statement to fail out on CentOS5 earlier in the test module?

Sourcing ~/.ascrc will succeed, but the tests did at least log warn on testr.

**Comment by taldcroft** [comment]
It's not really a question of "failing out".  Instead, identify a required test dependency early on (`HAS_ASCDS`) and then `@pytest.mark.skipif('not HAS_ASCDS')` any tests that require ASCDS.  This is mostly being done already, except that the test for ASCDS is not robust.

**Comment by jeanconn** [comment]
Closed by #10
