### ISSUE TITLE
Specifying report location when re-running agasc-update-magnitudes

### ISSUE THREAD

**Issue by javierggt** [sot/agasc#90]
Currently, `agasc-update-magnitudes` takes a `--reports-dir` argument. Initially I intended this to be the top-level directory for reports, and the actual subdirectory is set automatically using the date. This is ok for weekly runs.

When I re-run the script using the `--obs-status-file obs_status.yml` argument, the date is not specified anymore (currently --obs-status-file and `--start/stop` are not used together), but the script needs to find the right report directory in order to update it.

Two ways to fix it:
- add a `--reports-subdir` option
- make `--obs-status-file` and `--start/stop` work together and stipulate that when re-running one has to pass the same arguments. That might actually be needed anyway if the `star_obs_catalogs.STARS_OBS` changed since the time when the script was run (i.e.: some stars in the run were observed after the script was run)

**Comment by taldcroft** [comment]
Effectively, the idea now is to also output a `call_args.yml` file which encapsulates the calling arguments.

A subsequent call to the update script can then do `--call-args-file=call_args.yml` to read the previous call args and exactly replicate the original processing start/stop times, etc.

**Comment by javierggt** [comment]
For the record, what I am doing in PR #92 is specifying the `report_date` as argument to the function. The docstring mentions that the report subdirectory will be the first 8 characters of the date. If the date is not given (which does not happen in the script), the report will be inside `reports_dir` (one level up) and the date gets set to `CxoTime.now()`
