### ISSUE TITLE
Known-bad observation is included

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#94]
898124000 and 898125104 showed up in the mission obs_status.yml but they are from a Venus observation obsid 16505.

**Comment by javierggt** [comment]
The agasc supplement does not include functionality to distinguish that. There is a list in `mica.bad_obsids` and the magnitude estimation does not use it currently. We discussed whether to set an obs status using `mica.bad_obsids`, and decided not to do it, but use `obs` table to also store info on Venus observations.

That means we need to create an obs-status.yml file with all Venus observations to include in the supplement.

**Comment by javierggt** [comment]
This was fixed as part of a large update of the supplement which included all Venus observations.
